location          = "West Europe"
environment       = "prod"
acr_name          = "crappjavatest"
acr_rg_name       = "rg-main"
docker_image      = "crappjavatest/rc-app-java"
db_connect_string = "jdbc:postgresql://137.116.192.131:5432/qa_db"
